module VideoSegmentsHelper

  def video_segment_thumbnail_html video_segment, args = {}
    args[:class] ||= []
    args[:class] = args[:class].join(' ') if args[:class].is_a? Array
    args = args.merge({
      :class => "video-segment-thumbnail #{args[:class]}",
      :alt => (video_segment.nil? ? nil : video_segment.name),
      :width => args[:width],
      :height => args[:height],
      :crop => :center})
    thumbnail = video_segment.thumbnail || video_segment.video.thumbnail
    if args[:dynamic] || nil
      dynamic_thumbnail_html thumbnail, args
    else
      thumbnail_html thumbnail, args
    end
  end
  safe_helper :video_segment_thumbnail_html

  # Not auto-generated by routes since we are pointing to a video
  def video_segment_video_path segment, options = {}
    video_segment_video_url(segment, options.merge({:only_path => true}))
  end

  def video_segment_video_url segment, options = {}
    options = options.merge({:start => segment.start_time})
    path = !segment.video.permalink.nil? ? video_url(segment.video.permalink, options) : video_url(segment.video, options)
    path
  end

end
